import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Navbar from './components/navbar/Navbar';
import classNames from 'classnames/bind';
import Main from '../app/components/main/Card';

import styles from './styles/global.module.scss';

const cx = classNames.bind(styles);

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: '먹어보는거야 - 푸드비앤비',
  description: 'Generated by SH & KJ',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={cx([inter.className, 'body'])}>
        <ClientOnly>
          <Navbar />
        </ClientOnly>
        <div>{children}</div>
      </body>
    </html>
  );
}
