import { Inter } from 'next/font/google';
import classNames from 'classnames/bind';
import styles from '../styles/global.module.scss';

const cx = classNames.bind(styles);

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={cx([inter.className, 'body'])}>{children}</body>
    </html>
  );
}
